// recipeCatalogItaliana.js — Tercer catálogo: cocina italiana. Contenido
// redactado íntegramente para FoodStock (no copiado de ninguna fuente
// concreta): listas de ingredientes y pasos funcionales de platos de
// conocimiento popular, con cantidades orientativas para 4 personas.
//
// Formato compacto: [nombre, minutos, dificultad, categoría, ingredientes "nombre|cantidad|unidad", pasos, nutrición]

const RAW = [
  // --- Antipasti ---
  ['Bruschetta al pomodoro', 15, 'Fácil', 'Rápida', ['Pan|1|unidades', 'Tomate|4|unidades', 'Aceite|30|ml'], ['Tuesta rebanadas de pan', 'Frota con ajo', 'Corta el tomate en dados y mezcla con albahaca y aceite', 'Reparte el tomate sobre el pan'], { calories: 220, protein: 5, carbs: 28, fat: 9 }],
  ['Caprese di bufala', 10, 'Fácil', 'Rápida', ['Tomate|4|unidades', 'Queso|250|g'], ['Corta el tomate y la mozzarella de búfala en rodajas', 'Alterna capas en un plato', 'Añade hojas de albahaca fresca', 'Aliña con aceite de oliva y sal'], { calories: 280, protein: 16, carbs: 8, fat: 21 }],
  ['Carpaccio de ternera', 15, 'Media', 'Rápida', ['Ternera|300|g', 'Aceite|30|ml'], ['Congela ligeramente la carne para cortarla más fácil', 'Corta láminas muy finas', 'Reparte en un plato', 'Aliña con aceite, limón, rúcula y queso en virutas'], { calories: 240, protein: 26, carbs: 1, fat: 15 }],
  ['Vitello tonnato', 40, 'Media', 'Tradicional', ['Ternera|500|g', 'Atún|100|g'], ['Cuece la ternera en caldo con verduras', 'Deja enfriar y corta en láminas finas', 'Prepara una salsa de atún, mayonesa y alcaparras', 'Cubre la carne con la salsa y enfría antes de servir'], { calories: 320, protein: 30, carbs: 4, fat: 20 }],
  ['Involtini de berenjena', 35, 'Media', 'Vegetariana', ['Berenjena|2|unidades', 'Queso|150|g', 'Tomate|300|g'], ['Corta la berenjena en láminas finas y hornéalas', 'Rellena cada lámina con queso y enróllala', 'Coloca en una fuente con salsa de tomate', 'Gratina en el horno 15 minutos'], { calories: 260, protein: 12, carbs: 14, fat: 17 }],
  ['Focaccia italiana', 50, 'Media', 'Económica', ['Harina|400|g', 'Aceite|60|ml'], ['Prepara una masa con harina, agua, levadura y sal', 'Deja fermentar hasta doblar el volumen', 'Extiende en una bandeja y marca hoyos con los dedos', 'Riega con aceite, romero y sal gorda, y hornea a 220°C 20 minutos'], { calories: 260, protein: 6, carbs: 42, fat: 8 }],
  ['Arancini de risotto', 45, 'Media', 'Tradicional', ['Arroz|300|g', 'Queso|100|g', 'Huevos|2|unidades'], ['Prepara un risotto y déjalo enfriar', 'Forma bolas rellenas de queso', 'Empana con huevo y pan rallado', 'Fríe en aceite bien caliente hasta dorar'], { calories: 340, protein: 10, carbs: 44, fat: 14 }],
  ['Antipasto misto', 15, 'Fácil', 'Rápida', ['Queso|150|g', 'Aceitunas|100|g', 'Tomate|2|unidades'], ['Corta quesos y embutidos en lonchas', 'Añade tomates cherry y aceitunas', 'Reparte todo en una tabla', 'Riega con aceite de oliva'], { calories: 320, protein: 16, carbs: 8, fat: 25 }],

  // --- Pasta ---
  ['Spaghetti aglio e olio', 15, 'Fácil', 'Rápida', ['Pasta|350|g', 'Aceite|60|ml'], ['Cuece la pasta en agua con sal', 'Calienta el aceite con ajo laminado y guindilla', 'Escurre la pasta y saltéala con el aceite aromatizado', 'Añade perejil picado y sirve'], { calories: 460, protein: 11, carbs: 68, fat: 16 }],
  ['Penne arrabbiata', 20, 'Fácil', 'Rápida', ['Pasta|350|g', 'Tomate|400|g', 'Aceite|30|ml'], ['Sofríe ajo y guindilla en aceite', 'Añade el tomate triturado y cuece 10 minutos', 'Cuece la pasta y escurre', 'Mezcla la pasta con la salsa picante'], { calories: 440, protein: 12, carbs: 72, fat: 11 }],
  ['Pasta alla puttanesca', 25, 'Fácil', 'Rápida', ['Pasta|350|g', 'Tomate|400|g', 'Aceitunas|80|g'], ['Sofríe ajo, anchoas y alcaparras en aceite', 'Añade el tomate y las aceitunas y cuece 10 minutos', 'Cuece la pasta y escurre', 'Mezcla la pasta con la salsa'], { calories: 450, protein: 13, carbs: 70, fat: 13 }],
  ['Pasta al pesto genovés', 15, 'Fácil', 'Rápida', ['Pasta|350|g', 'Albahaca|50|g', 'Aceite|60|ml'], ['Tritura albahaca, piñones, ajo y queso con el aceite', 'Cuece la pasta en agua con sal', 'Escurre reservando un poco de agua de cocción', 'Mezcla la pasta con el pesto y un poco de agua'], { calories: 480, protein: 13, carbs: 66, fat: 19 }],
  ['Lasaña boloñesa', 60, 'Media', 'Tradicional', ['Carne picada|500|g', 'Tomate|400|g', 'Leche|400|ml', 'Queso|150|g'], ['Prepara una salsa boloñesa con la carne y el tomate', 'Prepara una bechamel con la leche', 'Alterna capas de pasta, boloñesa y bechamel', 'Cubre con queso y gratina 25 minutos'], { calories: 480, protein: 26, carbs: 38, fat: 24 }],
  ['Ravioles de ricotta y espinacas', 35, 'Media', 'Vegetariana', ['Espinacas|300|g', 'Queso|200|g', 'Harina|300|g'], ['Prepara una masa de pasta fresca y estírala fina', 'Rellena con ricotta y espinacas salteadas', 'Cierra los ravioles bien sellados', 'Cuece en agua hirviendo 3-4 minutos y sirve con mantequilla y salvia'], { calories: 380, protein: 16, carbs: 48, fat: 14 }],
  ['Tortellini en caldo', 30, 'Media', 'Tradicional', ['Pollo|300|g', 'Harina|250|g', 'Queso|100|g'], ['Prepara un caldo de pollo casero', 'Rellena pequeños tortellini con carne y queso', 'Cuece los tortellini en el caldo hirviendo', 'Sirve en el propio caldo bien caliente'], { calories: 340, protein: 20, carbs: 38, fat: 11 }],
  ['Pasta con salsa de nata y champiñones', 20, 'Fácil', 'Rápida', ['Pasta|350|g', 'Champiñones|300|g', 'Leche|200|ml'], ['Saltea los champiñones laminados', 'Añade nata o leche y reduce a fuego suave', 'Cuece la pasta y escurre', 'Mezcla la pasta con la salsa'], { calories: 460, protein: 13, carbs: 62, fat: 17 }],
  ['Fettuccine Alfredo', 20, 'Fácil', 'Rápida', ['Pasta|350|g', 'Queso|150|g', 'Leche|150|ml'], ['Cuece la pasta en agua con sal', 'Funde mantequilla con la leche a fuego suave', 'Añade queso rallado y remueve hasta cremar', 'Mezcla con la pasta escurrida'], { calories: 500, protein: 16, carbs: 62, fat: 20 }],
  ['Pasta alla norma', 25, 'Fácil', 'Vegetariana', ['Pasta|350|g', 'Berenjena|2|unidades', 'Tomate|400|g'], ['Fríe la berenjena en dados hasta dorar', 'Prepara una salsa de tomate con ajo y albahaca', 'Mezcla la berenjena con la salsa', 'Cuece la pasta y mezcla todo, con queso rallado por encima'], { calories: 440, protein: 11, carbs: 68, fat: 14 }],
  ['Orecchiette con brócoli', 25, 'Fácil', 'Saludable', ['Pasta|350|g', 'Brócoli|1|unidades', 'Aceite|30|ml'], ['Cuece el brócoli hasta que esté tierno', 'Cuece la pasta en la misma agua', 'Saltea ajo y anchoas en aceite', 'Mezcla la pasta, el brócoli y el aceite aromatizado'], { calories: 400, protein: 14, carbs: 66, fat: 9 }],
  ['Linguine alle vongole', 25, 'Media', 'Tradicional', ['Pasta|350|g', 'Almejas|500|g', 'Aceite|40|ml'], ['Cuece la pasta en agua con sal', 'Saltea las almejas con ajo hasta que se abran', 'Añade vino blanco y deja reducir', 'Mezcla la pasta escurrida con las almejas y su jugo'], { calories: 460, protein: 20, carbs: 66, fat: 12 }],
  ['Rigatoni con salchicha italiana', 25, 'Fácil', 'Rápida', ['Pasta|350|g', 'Salchicha|300|g', 'Tomate|300|g'], ['Dora la salchicha desmenuzada', 'Añade el tomate y cuece 10 minutos', 'Cuece la pasta y escurre', 'Mezcla la pasta con la salsa y queso rallado'], { calories: 490, protein: 20, carbs: 62, fat: 18 }],
  ['Pasta al horno con berenjena', 45, 'Media', 'Vegetariana', ['Pasta|350|g', 'Berenjena|2|unidades', 'Queso|150|g'], ['Cuece la pasta al dente', 'Saltea la berenjena en dados', 'Mezcla pasta, berenjena y salsa de tomate', 'Cubre con queso y gratina 15 minutos'], { calories: 440, protein: 15, carbs: 60, fat: 15 }],
  ['Gnocchi al pesto', 15, 'Fácil', 'Rápida', ['Ñoquis|500|g', 'Albahaca|40|g', 'Aceite|50|ml'], ['Cuece los ñoquis hasta que floten', 'Prepara o calienta el pesto', 'Escurre los ñoquis', 'Mezcla con el pesto y sirve'], { calories: 420, protein: 10, carbs: 60, fat: 15 }],
  ['Cannelloni de ricotta', 50, 'Media', 'Vegetariana', ['Espinacas|300|g', 'Queso|250|g', 'Leche|300|ml'], ['Saltea las espinacas y mézclalas con ricotta', 'Rellena los canelones con la mezcla', 'Cubre con bechamel y queso', 'Gratina en el horno 20-25 minutos'], { calories: 380, protein: 17, carbs: 34, fat: 19 }],

  // --- Risotto ---
  ['Risotto alla milanese', 35, 'Media', 'Tradicional', ['Arroz|300|g', 'Cebolla|1|unidades', 'Queso|60|g'], ['Sofríe la cebolla y añade el arroz nacarándolo', 'Añade caldo con azafrán poco a poco removiendo', 'Cuece hasta que el arroz esté cremoso', 'Termina con mantequilla y queso rallado'], { calories: 420, protein: 10, carbs: 68, fat: 11 }],
  ['Risotto de calabaza', 35, 'Fácil', 'Vegetariana', ['Arroz|300|g', 'Calabaza|400|g', 'Cebolla|1|unidades'], ['Sofríe la cebolla y añade la calabaza en dados', 'Incorpora el arroz y nácara un par de minutos', 'Añade caldo caliente poco a poco removiendo', 'Cocina hasta que quede cremoso y añade queso'], { calories: 400, protein: 9, carbs: 70, fat: 9 }],
  ['Risotto de espárragos', 35, 'Fácil', 'Vegetariana', ['Arroz|300|g', 'Espárragos|1|latas', 'Cebolla|1|unidades'], ['Sofríe la cebolla y añade el arroz', 'Añade caldo poco a poco removiendo', 'Incorpora los espárragos troceados a mitad de cocción', 'Termina con queso rallado'], { calories: 390, protein: 9, carbs: 68, fat: 8 }],
  ['Risotto de gambas', 35, 'Media', 'Tradicional', ['Arroz|300|g', 'Gambas|300|g', 'Cebolla|1|unidades'], ['Saltea las gambas y resérvalas', 'Sofríe la cebolla y añade el arroz', 'Añade caldo de pescado poco a poco', 'Incorpora las gambas al final y remueve'], { calories: 420, protein: 20, carbs: 62, fat: 9 }],
  ['Risotto al vino tinto', 35, 'Media', 'Tradicional', ['Arroz|300|g', 'Cebolla|1|unidades', 'Queso|60|g'], ['Sofríe la cebolla y añade el arroz', 'Añade un buen chorro de vino tinto y deja evaporar', 'Incorpora caldo poco a poco removiendo', 'Termina con mantequilla y queso rallado'], { calories: 410, protein: 9, carbs: 66, fat: 10 }],

  // --- Pizza ---
  ['Pizza margarita', 40, 'Media', 'Económica', ['Harina|300|g', 'Tomate|300|g', 'Queso|200|g'], ['Prepara la masa con harina, agua, levadura y sal', 'Deja fermentar y estírala fina', 'Cubre con tomate, mozzarella y albahaca', 'Hornea a máxima temperatura 8-10 minutos'], { calories: 320, protein: 13, carbs: 44, fat: 10 }],
  ['Pizza cuatro quesos', 40, 'Media', 'Rápida', ['Harina|300|g', 'Queso|300|g'], ['Estira la masa de pizza', 'Reparte cuatro tipos de queso diferentes', 'Hornea a máxima temperatura hasta gratinar', 'Sirve recién salida del horno'], { calories: 380, protein: 18, carbs: 40, fat: 17 }],
  ['Pizza de jamón y champiñones', 40, 'Media', 'Rápida', ['Harina|300|g', 'Champiñones|200|g', 'Queso|200|g'], ['Estira la masa y cubre con tomate', 'Reparte jamón y champiñones laminados', 'Añade queso mozzarella', 'Hornea a máxima temperatura 10 minutos'], { calories: 350, protein: 16, carbs: 42, fat: 13 }],
  ['Pizza vegetariana', 40, 'Media', 'Vegetariana', ['Harina|300|g', 'Pimiento|1|unidades', 'Calabacín|1|unidades', 'Queso|200|g'], ['Estira la masa y cubre con tomate', 'Reparte verduras variadas en juliana', 'Añade queso mozzarella', 'Hornea a máxima temperatura 10 minutos'], { calories: 300, protein: 12, carbs: 42, fat: 9 }],
  ['Calzone relleno', 45, 'Media', 'Tradicional', ['Harina|300|g', 'Queso|200|g', 'Tomate|150|g'], ['Estira la masa en forma de círculo', 'Rellena media parte con tomate, queso y jamón', 'Dobla y sella bien los bordes', 'Hornea a 220°C 15-18 minutos'], { calories: 400, protein: 17, carbs: 46, fat: 16 }],
  ['Pizza de pepperoni', 40, 'Media', 'Rápida', ['Harina|300|g', 'Tomate|250|g', 'Queso|200|g'], ['Estira la masa y cubre con tomate', 'Reparte queso mozzarella y pepperoni', 'Hornea a máxima temperatura 10 minutos', 'Sirve recién horneada'], { calories: 380, protein: 16, carbs: 42, fat: 16 }],

  // --- Secondi (carnes y pescados) ---
  ['Pollo alla cacciatora', 45, 'Media', 'Tradicional', ['Pollo|800|g', 'Tomate|400|g', 'Cebolla|1|unidades'], ['Dora el pollo troceado', 'Sofríe cebolla y pimiento', 'Añade el tomate y un chorro de vino', 'Cuece a fuego lento 25-30 minutos'], { calories: 380, protein: 34, carbs: 12, fat: 20 }],
  ['Escalopines a la milanesa', 25, 'Fácil', 'Rápida', ['Ternera|600|g', 'Huevos|2|unidades'], ['Aplana los filetes de ternera', 'Pasa por huevo y pan rallado', 'Fríe en aceite bien caliente hasta dorar', 'Sirve con limón y ensalada'], { calories: 380, protein: 34, carbs: 18, fat: 18 }],
  ['Ossobuco a la milanesa', 90, 'Difícil', 'Tradicional', ['Ternera|1|kg', 'Tomate|300|g', 'Cebolla|1|unidades'], ['Dora los ossobuco en la olla', 'Añade cebolla, zanahoria y vino blanco', 'Incorpora tomate y caldo', 'Cuece a fuego lento 1.5-2 horas hasta que esté tierno'], { calories: 460, protein: 38, carbs: 12, fat: 26 }],
  ['Saltimbocca a la romana', 20, 'Fácil', 'Rápida', ['Ternera|500|g', 'Aceite|20|ml'], ['Coloca una hoja de salvia sobre cada filete', 'Envuelve con una loncha de jamón', 'Dora en mantequilla por ambos lados', 'Añade vino blanco y reduce la salsa'], { calories: 340, protein: 32, carbs: 2, fat: 21 }],
  ['Ternera al marsala', 30, 'Media', 'Tradicional', ['Ternera|500|g', 'Champiñones|200|g'], ['Dora los filetes de ternera', 'Saltea los champiñones', 'Añade vino de marsala y deja reducir', 'Cocina 5 minutos más hasta que la salsa espese'], { calories: 360, protein: 32, carbs: 8, fat: 20 }],
  ['Bacalao a la italiana', 30, 'Fácil', 'Saludable', ['Bacalao|600|g', 'Tomate|400|g', 'Aceitunas|60|g'], ['Sofríe ajo, tomate y alcaparras', 'Añade el bacalao a la salsa', 'Cuece 10-12 minutos a fuego suave', 'Añade aceitunas y perejil antes de servir'], { calories: 280, protein: 32, carbs: 10, fat: 11 }],
  ['Salmón al limón y alcaparras', 20, 'Fácil', 'Saludable', ['Salmón|600|g', 'Aceite|20|ml'], ['Salpimienta los lomos de salmón', 'Cocina a la plancha por ambos lados', 'Prepara una salsa con limón, alcaparras y aceite', 'Sirve el salmón con la salsa por encima'], { calories: 340, protein: 34, carbs: 2, fat: 21 }],
  ['Pollo a la parmesana', 35, 'Media', 'Rápida', ['Pollo|600|g', 'Tomate|300|g', 'Queso|150|g'], ['Empana los filetes de pollo y fríelos', 'Colócalos en una fuente con salsa de tomate', 'Cubre con queso mozzarella', 'Gratina en el horno 10-12 minutos'], { calories: 420, protein: 36, carbs: 18, fat: 22 }],
  ['Albóndigas italianas en salsa', 45, 'Fácil', 'Económica', ['Carne picada|500|g', 'Tomate|400|g', 'Huevos|1|unidades'], ['Mezcla la carne con huevo, pan rallado, ajo y albahaca', 'Forma las albóndigas y dóralas', 'Prepara una salsa de tomate', 'Cuece las albóndigas en la salsa 20 minutos'], { calories: 380, protein: 25, carbs: 16, fat: 23 }],
  ['Lomo a la pizzaiola', 30, 'Fácil', 'Rápida', ['Lomo de cerdo|600|g', 'Tomate|400|g'], ['Dora los filetes de lomo', 'Añade tomate, orégano y ajo', 'Cuece a fuego lento 15 minutos', 'Sirve con la salsa por encima'], { calories: 320, protein: 30, carbs: 10, fat: 16 }],

  // --- Contorni ---
  ['Espinacas salteadas al ajo', 12, 'Fácil', 'Saludable', ['Espinacas|400|g', 'Aceite|20|ml'], ['Calienta el aceite con ajo laminado', 'Añade las espinacas', 'Saltea hasta que reduzcan', 'Ajusta de sal y sirve'], { calories: 90, protein: 4, carbs: 6, fat: 6 }],
  ['Judías verdes con tomate italiano', 25, 'Fácil', 'Saludable', ['Judías verdes|400|g', 'Tomate|300|g'], ['Cuece las judías verdes al dente', 'Sofríe ajo y tomate con albahaca', 'Añade las judías escurridas', 'Cocina 5 minutos más juntas'], { calories: 130, protein: 4, carbs: 16, fat: 6 }],
  ['Patatas al romero', 35, 'Fácil', 'Económica', ['Patatas|600|g', 'Aceite|40|ml'], ['Corta las patatas en cuartos', 'Mezcla con aceite, romero y ajo', 'Extiende en una bandeja de horno', 'Hornea a 200°C 30-35 minutos'], { calories: 240, protein: 4, carbs: 36, fat: 9 }],
  ['Coliflor gratinada', 35, 'Fácil', 'Vegetariana', ['Coliflor|1|unidades', 'Leche|300|ml', 'Queso|100|g'], ['Cuece la coliflor en ramilletes', 'Prepara una bechamel ligera', 'Coloca la coliflor en una fuente y cubre con la bechamel', 'Gratina con queso en el horno 15 minutos'], { calories: 210, protein: 9, carbs: 16, fat: 12 }],
  ['Ensalada de rúcula y parmesano', 10, 'Fácil', 'Saludable', ['Rúcula|150|g', 'Queso|60|g', 'Aceite|30|ml'], ['Lava y escurre la rúcula', 'Añade virutas de queso parmesano', 'Aliña con aceite y limón', 'Sirve fresco'], { calories: 160, protein: 8, carbs: 4, fat: 13 }],

  // --- Dolci ---
  ['Cannoli sicilianos', 45, 'Media', 'Postre', ['Harina|250|g', 'Queso|300|g', 'Aceite|300|ml'], ['Prepara una masa fina y enróllala en tubos', 'Fríe los tubos hasta dorar y deja enfriar', 'Bate la ricotta con azúcar y chocolate', 'Rellena los cannoli justo antes de servir'], { calories: 340, protein: 8, carbs: 32, fat: 20 }],
  ['Affogato al café', 8, 'Fácil', 'Postre', ['Café|1|unidades'], ['Prepara un café espresso bien caliente', 'Coloca una bola de helado de vainilla en un vaso', 'Vierte el café caliente por encima', 'Sirve inmediatamente'], { calories: 180, protein: 3, carbs: 22, fat: 8 }],
  ['Zabaglione', 15, 'Media', 'Postre', ['Huevos|4|unidades'], ['Bate las yemas con azúcar hasta blanquear', 'Añade vino marsala poco a poco', 'Cocina al baño maría batiendo sin parar', 'Sirve templado en copas cuando espese'], { calories: 220, protein: 6, carbs: 20, fat: 9 }],
  ['Torta caprese', 50, 'Media', 'Postre', ['Chocolate|200|g', 'Almendras|200|g', 'Huevos|4|unidades'], ['Funde el chocolate con mantequilla', 'Bate huevos con azúcar e incorpora el chocolate', 'Añade almendra molida', 'Hornea a 170°C 35-40 minutos'], { calories: 400, protein: 8, carbs: 30, fat: 28 }],
  ['Semifreddo de limón', 30, 'Media', 'Postre', ['Huevos|3|unidades', 'Limón|3|unidades'], ['Bate las yemas con azúcar y zumo de limón', 'Monta la nata y las claras por separado', 'Mezcla todo con cuidado', 'Congela en un molde al menos 4 horas'], { calories: 260, protein: 5, carbs: 22, fat: 17 }],
  ['Biscotti de almendra', 40, 'Media', 'Postre', ['Harina|300|g', 'Almendras|150|g', 'Huevos|3|unidades'], ['Mezcla harina, azúcar, huevo y almendras', 'Forma dos troncos y hornea 20 minutos', 'Deja enfriar un poco y corta en rebanadas', 'Vuelve a hornear las rebanadas 10 minutos para que queden crujientes'], { calories: 220, protein: 6, carbs: 28, fat: 9 }],
  ['Panettone casero', 120, 'Difícil', 'Postre', ['Harina|500|g', 'Huevos|4|unidades', 'Leche|150|ml'], ['Prepara una masa enriquecida con huevo y mantequilla', 'Deja fermentar varias horas hasta doblar', 'Añade fruta escarchada y pasas', 'Hornea a 180°C 35-40 minutos'], { calories: 320, protein: 7, carbs: 44, fat: 12 }],
  ['Crostata de frutas', 55, 'Media', 'Postre', ['Harina|250|g', 'Fruta|400|g', 'Huevos|1|unidades'], ['Prepara una masa quebrada y fórrala en un molde', 'Cubre con mermelada o crema pastelera', 'Coloca fruta fresca en abanico', 'Hornea a 180°C 30-35 minutos'], { calories: 280, protein: 4, carbs: 42, fat: 11 }],
  ['Budino de chocolate', 20, 'Fácil', 'Postre', ['Chocolate|150|g', 'Leche|500|ml'], ['Calienta la leche con el chocolate troceado', 'Disuelve maicena en un poco de leche fría y añádela', 'Cuece removiendo hasta que espese', 'Reparte en vasitos y enfría antes de servir'], { calories: 260, protein: 5, carbs: 30, fat: 13 }],
  ['Panna cotta de café', 20, 'Fácil', 'Postre', ['Leche|500|ml', 'Café|1|unidades'], ['Calienta la nata con azúcar y café espresso', 'Disuelve gelatina hidratada en la mezcla caliente', 'Reparte en moldes individuales', 'Enfría al menos 4 horas antes de desmoldar'], { calories: 270, protein: 4, carbs: 20, fat: 19 }],
  ['Tiramisú clásico', 30, 'Media', 'Postre', ['Queso|250|g', 'Huevos|3|unidades', 'Café|1|unidades'], ['Bate las yemas con azúcar hasta blanquear', 'Mezcla con el queso mascarpone', 'Moja bizcochos de soletilla en café y monta capas', 'Cubre con la crema y cacao en polvo, enfría 4 horas'], { calories: 340, protein: 7, carbs: 26, fat: 22 }],
];

export const RECIPE_CATALOG_ITALIANA = RAW.map(([name, time, difficulty, category, ingLines, steps, nutrition]) => ({
  name,
  photo: null,
  time,
  difficulty,
  category,
  favorite: false,
  ingredients: ingLines.map((line) => {
    const [ingName, quantity, unit] = line.split('|');
    return { name: ingName, quantity: quantity ? Number(quantity) : null, unit: unit || 'unidades' };
  }),
  steps,
  nutrition,
}));
